name: Docker Image CI
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          submodules: recursive
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx Branch
        run: |
          docker buildx build --file Dockerfile .
        if: github.ref != 'refs/heads/master'
      - name: Run Buildx Master
        run: |
          docker buildx build --file Dockerfile . -t polycubenetwork/polycube-codegen
        if: github.ref == 'refs/heads/master'
      - name: Push image on repo
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: polycubenetwork/polycube-codegen
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
